### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by JSanders24** [mikeizbicki/pagila-midterm#1]
I am currently trying to see the output of my sql queries but get a permission denied error when trying to build the docker container. Any ideas for how to resolve this issue?

```
`Julian.Sanders.24@lambda-server:~/pagila-midterm$ docker-compose up -d --build
-bash: /usr/bin/docker-compose: Permission denied
Julian.Sanders.24@lambda-server:~/pagila-midterm$ git submodule init
Julian.Sanders.24@lambda-server:~/pagila-midterm$ git submodule update
Julian.Sanders.24@lambda-server:~/pagila-midterm$ docker-compose up -d --build
-bash: /usr/bin/docker-compose: Permission denied
Julian.Sanders.24@lambda-server:~/pagila-midterm$ chmod +x /usr/bin/docker-compose
chmod: changing permissions of '/usr/bin/docker-compose': Operation not permitted`
```

**Comment by mikeizbicki** [comment]
Recall that the instructions for the midterm in the README state:

> You may not collaborate with any human on this assignment. In particular, you cannot:
>
>   1. work with another student,
>   2. or post questions on github/stackoverflow.

Anyone needing to ask questions may contact me over email, but I cannot guarantee that I will be able to answer.
